ARG NGINX_VERSION=1.25.3
FROM nginx:${NGINX_VERSION}
ARG NGINX_VERSION

RUN --mount=type=cache,target=/var/cache/apt <<EOF
    set -eux
    export DEBIAN_FRONTEND=noninteractive
    apt-get -qq update
    apt-get -qq install --yes --no-install-recommends --no-install-suggests \
        curl gnupg2 ca-certificates debian-archive-keyring inotify-tools
    update-ca-certificates
    apt-get remove --purge --auto-remove --yes
EOF

RUN mkdir -p /usr/lib/nginx/njs_modules
RUN mkdir -p /etc/nginx/njs-acme
RUN chown nginx: /etc/nginx/njs-acme
