name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test with nginx ${{ matrix.nginx-version }}
    strategy:
      matrix:
        nginx-version:
          - 1.25.x
    env:
      NGINX_VERSION: ${{ matrix.nginx-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: sudo apt-get install -y ca-certificates
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:unit
      - run: make docker-integration-tests
