name: License Scanning

on:
  - pull_request
  - push

jobs:
  fossa:
    # This job is only useful when run on upstream
    if: github.repository == 'nginxinc/ngx-rust' || github.event_name == 'workflow_dispatch'
    runs-on: FOSSA scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v2
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
