name: Upload acme.js to release page

on:
  release:
    types: [created]

jobs:
  build:
    name: Build release artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build dist/acme.js
        run: make build

      - name: Upload acme.js to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/acme.js
          asset_name: acme.js
          asset_content_type: text/javascript
