name: Upload acme.js to release page

on:
  release:
    types: [created]

jobs:
  build:
    name: Build release artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build dist/acme.js
        run: make build

      - name: Upload acme.js to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.event.release.tag_name }}" ./dist/acme.js
